### ISSUE TITLE
Resolve security flaws

### ISSUE THREAD

**Issue by cristianKumul** [SlothTechOfficial/blog#5]
This is an old project, so there are some vulnerabilities with its dependencies. The task is to solve all of them.

**Comment by oznakn** [comment]
I would like to take this issue if it is okey for you.

**Comment by cristianKumul** [comment]
> I would like to take this issue if it is okey for you.

Sounds good!. go ahead

**Comment by oznakn** [comment]
Hi, I updated the packages that have vulnerabilities in pr #6.

But apparently, the vulnerability in _webpack-cdn-plugin_ fixed after the package dropped webpack 3 support. So it is not possible to fix the vulnerability without migrating the webpack configs from 3 to 4. So I think that's another issue's topic.
